
import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SHAHEEN
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radCoffee = new javax.swing.JRadioButton();
        radCap = new javax.swing.JRadioButton();
        radTea = new javax.swing.JRadioButton();
        chkBag = new javax.swing.JCheckBox();
        chkCro = new javax.swing.JCheckBox();
        chkToa = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSub = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTax = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTot = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEnt = new javax.swing.JButton();
        btnCle = new javax.swing.JButton();
        btnExi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Coffee Shop");

        radCoffee.setText("Coffee 1.00");
        radCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCoffeeActionPerformed(evt);
            }
        });

        radCap.setText("Cappuccino 1.25");
        radCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCapActionPerformed(evt);
            }
        });

        radTea.setText("Tea 1.00");
        radTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTeaActionPerformed(evt);
            }
        });

        chkBag.setText("Bagels 1.25");

        chkCro.setText("Croissant 1.15");

        chkToa.setText("Toast 0.50");

        jScrollPane1.setViewportView(txtSub);

        jScrollPane2.setViewportView(txtTax);

        jScrollPane3.setViewportView(txtTot);

        jLabel2.setText("Subtotal");

        jLabel3.setText("Tax");

        jLabel4.setText("Total");

        btnEnt.setText("Enter");
        btnEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntActionPerformed(evt);
            }
        });

        btnCle.setText("Clear");
        btnCle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleActionPerformed(evt);
            }
        });

        btnExi.setText("Exit");
        btnExi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radCoffee)
                            .addComponent(radCap)
                            .addComponent(radTea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkToa)
                            .addComponent(chkCro)
                            .addComponent(chkBag))))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCoffee)
                    .addComponent(chkBag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCap)
                    .addComponent(chkCro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radTea)
                    .addComponent(chkToa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnEnt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnCle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnExi))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCoffeeActionPerformed
        // select coffee option
        if(radCoffee.isSelected())
            radCap.setSelected(false);
            radTea.setSelected(false);
    }//GEN-LAST:event_radCoffeeActionPerformed

    private void radCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCapActionPerformed
        // select cap
        if(radCap.isSelected())
            radCoffee.setSelected(false);
            radTea.setSelected(false);
    }//GEN-LAST:event_radCapActionPerformed

    private void radTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTeaActionPerformed
        // select tea option
        if(radTea.isSelected())
            radCap.setSelected(false);
            radCoffee.setSelected(false);
    }//GEN-LAST:event_radTeaActionPerformed

    private void btnEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntActionPerformed
        // TODO add your handling code here:
        
        DecimalFormat df = new DecimalFormat("0.00");
        double total;
        double subtotal = 0;
        final double TAXRATE = .08;
        double tax;
        
        if(radCoffee.isSelected()){
            subtotal = subtotal + 1;
        }else if (radCap.isSelected()){
            subtotal = subtotal + 1.25;
        }else if (radTea.isSelected()){
            subtotal = subtotal + 1;
        }
        
        if (chkBag.isSelected()){
            subtotal = subtotal + 1.25;
        }if (chkCro.isSelected()){
            subtotal = subtotal + 1.15;
        }if (chkToa.isSelected()){
            subtotal = subtotal + 0.5;
        }
        
        txtSub.setText(Double.toString(subtotal));
        
        subtotal = Double.parseDouble(txtSub.getText());
        tax = subtotal * TAXRATE;
        total = tax + subtotal;
        
        txtTax.setText(Double.toString(tax));
        txtTot.setText(Double.toString(total));
        
        txtTax.setText(df.format(tax));
        txtSub.setText(df.format(subtotal));
        txtTot.setText(df.format(total));
        
    }//GEN-LAST:event_btnEntActionPerformed

    private void btnExiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExiActionPerformed
        // exit JFrame
        System.exit(0);
    }//GEN-LAST:event_btnExiActionPerformed

    private void btnCleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleActionPerformed
        // Clear all fields
        radCoffee.setSelected(false);
        radTea.setSelected(false);
        radCap.setSelected(false);
        chkBag.setSelected(false);
        chkToa.setSelected(false);
        chkCro.setSelected(false);
        txtTot.setText("");
        txtSub.setText("");
        txtTax.setText("");
        
    }//GEN-LAST:event_btnCleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCle;
    private javax.swing.JButton btnEnt;
    private javax.swing.JButton btnExi;
    private javax.swing.JCheckBox chkBag;
    private javax.swing.JCheckBox chkCro;
    private javax.swing.JCheckBox chkToa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radCap;
    private javax.swing.JRadioButton radCoffee;
    private javax.swing.JRadioButton radTea;
    private javax.swing.JTextPane txtSub;
    private javax.swing.JTextPane txtTax;
    private javax.swing.JTextPane txtTot;
    // End of variables declaration//GEN-END:variables
}
